### ISSUE TITLE
I might be dumb, but

### ISSUE THREAD

**Issue by seiliu** [Laumania/RobloxPlayerNotifier#1]
how do you actually start the application

**Comment by Laumania** [comment]
You just have to double click the "RobloxPlayerNotifierApp.exe".

Doesn't that work?

**Comment by Laumania** [comment]
Oh and if this shows up, you have to click Run anyway:
![image](https://user-images.githubusercontent.com/1378458/74608037-362b7180-50de-11ea-9be5-771f2c9a2b03.png)

And then it should look like this:
![image](https://user-images.githubusercontent.com/1378458/74608054-4e9b8c00-50de-11ea-8710-6fdc12710061.png)

**Comment by seiliu** [comment]
I don't see the .exe, I think I might've installed it wrong. My friend told me I need to compile it in visual studio?

**Comment by seiliu** [comment]
![image](https://user-images.githubusercontent.com/58960625/74608327-0ebcb080-50ae-11ea-96f6-39043f7e5121.png)

**Comment by Laumania** [comment]
No no, don't download the code for the app, unless you want it, but if you just want to run it just get the zip file:
https://github.com/Laumania/RobloxPlayerNotifier/releases

**Comment by seiliu** [comment]
oh, thank you!

**Comment by Laumania** [comment]
No problem - you can see on the frontpage how you setup to notify about the players you want to know about.
